package com.clpsz.test.sharding.pay_order.domain;

import java.util.Date;

public class PayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fpay_order_id
     *
     * @mbggenerated
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fparent_pay_order_id
     *
     * @mbggenerated
     */
    private String parentPayOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fuid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Famount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fpay_way
     *
     * @mbggenerated
     */
    private Integer payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fpay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fpay_state
     *
     * @mbggenerated
     */
    private Integer payState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fsuc_trade_id
     *
     * @mbggenerated
     */
    private String sucTradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fversion
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fcreate_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order_0.Fmodify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fpay_order_id
     *
     * @return the value of t_pay_order_0.Fpay_order_id
     *
     * @mbggenerated
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fpay_order_id
     *
     * @param payOrderId the value for t_pay_order_0.Fpay_order_id
     *
     * @mbggenerated
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fparent_pay_order_id
     *
     * @return the value of t_pay_order_0.Fparent_pay_order_id
     *
     * @mbggenerated
     */
    public String getParentPayOrderId() {
        return parentPayOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fparent_pay_order_id
     *
     * @param parentPayOrderId the value for t_pay_order_0.Fparent_pay_order_id
     *
     * @mbggenerated
     */
    public void setParentPayOrderId(String parentPayOrderId) {
        this.parentPayOrderId = parentPayOrderId == null ? null : parentPayOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fuid
     *
     * @return the value of t_pay_order_0.Fuid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fuid
     *
     * @param uid the value for t_pay_order_0.Fuid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Famount
     *
     * @return the value of t_pay_order_0.Famount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Famount
     *
     * @param amount the value for t_pay_order_0.Famount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fpay_way
     *
     * @return the value of t_pay_order_0.Fpay_way
     *
     * @mbggenerated
     */
    public Integer getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fpay_way
     *
     * @param payWay the value for t_pay_order_0.Fpay_way
     *
     * @mbggenerated
     */
    public void setPayWay(Integer payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fpay_type
     *
     * @return the value of t_pay_order_0.Fpay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fpay_type
     *
     * @param payType the value for t_pay_order_0.Fpay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fpay_state
     *
     * @return the value of t_pay_order_0.Fpay_state
     *
     * @mbggenerated
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fpay_state
     *
     * @param payState the value for t_pay_order_0.Fpay_state
     *
     * @mbggenerated
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fsuc_trade_id
     *
     * @return the value of t_pay_order_0.Fsuc_trade_id
     *
     * @mbggenerated
     */
    public String getSucTradeId() {
        return sucTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fsuc_trade_id
     *
     * @param sucTradeId the value for t_pay_order_0.Fsuc_trade_id
     *
     * @mbggenerated
     */
    public void setSucTradeId(String sucTradeId) {
        this.sucTradeId = sucTradeId == null ? null : sucTradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fversion
     *
     * @return the value of t_pay_order_0.Fversion
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fversion
     *
     * @param version the value for t_pay_order_0.Fversion
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fcreate_time
     *
     * @return the value of t_pay_order_0.Fcreate_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fcreate_time
     *
     * @param createTime the value for t_pay_order_0.Fcreate_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order_0.Fmodify_time
     *
     * @return the value of t_pay_order_0.Fmodify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order_0.Fmodify_time
     *
     * @param modifyTime the value for t_pay_order_0.Fmodify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "PayOrder{" +
                "payOrderId='" + payOrderId + '\'' +
                ", parentPayOrderId='" + parentPayOrderId + '\'' +
                ", uid=" + uid +
                ", amount=" + amount +
                ", payWay=" + payWay +
                ", payType=" + payType +
                ", payState=" + payState +
                ", sucTradeId='" + sucTradeId + '\'' +
                ", version=" + version +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                '}';
    }
}