package com.clpsz.test.sharding.pay_order.dao;

import com.clpsz.test.sharding.pay_order.domain.PayOrder;

public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    int insert(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    int insertSelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    PayOrder selectByPrimaryKey(String payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrder record);
}